"""
app/handlers/autofix.py
V4 Sprint 8: Auto-Fix Engine — Bug fixes.

FIXED (Sprint 8):
  1. _apply_fix truncation: current[:4000] → full file (up to 16 000 chars).
     Files >16 000 chars now carry an explicit truncation marker so the LLM
     knows it is seeing a partial file and must NOT return the missing tail.
     Added safety guard: if response is <70 % of original length → reject.
  2. _apply_fix silent failure: {"raw": text} path now logged + returns current.
  3. _create_branch KeyError: ref["object"]["sha"] wrapped in KeyError guard.
     Previously an unexpected API response structure crashed run_autofix with
     an unhandled exception (not caught by `except GitHubError`).
"""

import base64
import logging
from typing import Optional

from app.github.client import gh_get, gh_post, gh_put, GitHubError
from app.ai.router import router
from app.core.logger import EventLogger

log = logging.getLogger(__name__)

ALLOWED_EXTENSIONS = {".py", ".md", ".txt", ".yml", ".yaml", ".json", ".toml"}
BLOCKED_PATHS = {"app/github/auth.py", "server.py", ".env"}

# Sprint 8 fix: safe file-size limits.
# LLM context window is ~8 k tokens; 16 000 chars ≈ 4 000 tokens leaving
# room for system prompt + JSON response.
_MAX_FILE_CHARS = 16_000
_TRUNCATION_MARKER = (
    "\n\n# [AUTOFIX NOTE: FILE TRUNCATED AT {limit} CHARS — "
    "DO NOT REMOVE CONTENT AFTER THIS POINT IN YOUR RESPONSE]\n"
)


def run_autofix(
    repo: str,
    issue_number: int,
    issue: dict,
    token: str,
    target_file: str = "",
) -> str:
    """
    Entry point for /autofix command.
    Returns a Markdown string suitable for posting as a GitHub comment.
    """
    log_ctx = EventLogger("autofix", repo=repo)
    title = issue.get("title", "")
    body = (issue.get("body") or "")[:2000]

    fix_plan = _generate_fix_plan(title, body, target_file)
    if not fix_plan:
        return "## ⚠️ Autofix Failed\n\nCould not generate fix. Try `/fix` instead."

    target = fix_plan.get("target_file", target_file)
    if not _is_allowed(target):
        return (
            f"## ⚠️ Autofix Skipped\n\nCannot auto-modify `{target}`. "
            f"Use `/fix` manually."
        )

    # ── Read target file ───────────────────────────────────────────────────
    try:
        file_data = gh_get(f"/repos/{repo}/contents/{target}", token)
        current = base64.b64decode(file_data["content"]).decode("utf-8")
        file_sha = file_data["sha"]
    except Exception as e:
        return f"## ⚠️ Autofix Failed\n\nCannot read `{target}`: `{str(e)[:100]}`"

    # ── Generate fix ───────────────────────────────────────────────────────
    fixed = _apply_fix(current, fix_plan, title)
    if not fixed or fixed == current:
        return (
            "## ⚠️ Autofix Skipped\n\n"
            "Fix didn't change file. Use `/fix` for suggestions."
        )

    # ── Create branch ──────────────────────────────────────────────────────
    branch = f"fix/bot-issue-{issue_number}"
    default_br = _get_default_branch(repo, token)
    try:
        _create_branch(repo, token, branch, default_br)
    except GitHubError as e:
        if "already exists" not in str(e):
            return f"## ⚠️ Branch Error\n\n`{str(e)[:100]}`"
    except Exception as e:
        # Sprint 8 fix: _create_branch can raise KeyError (unexpected API
        # response structure) which is NOT a GitHubError. Catch and surface.
        log.error(f"autofix._create_branch unexpected error: {e}")
        return f"## ⚠️ Branch Error\n\nUnexpected error creating branch: `{str(e)[:100]}`"

    # ── Commit file ────────────────────────────────────────────────────────
    try:
        gh_put(
            f"/repos/{repo}/contents/{target}",
            token,
            {
                "message": (
                    f"fix: {fix_plan.get('commit_message', f'fix issue #{issue_number}')}\n\n"
                    f"Closes #{issue_number}\nAuto-generated by AI Repo Manager"
                ),
                "content": base64.b64encode(fixed.encode()).decode(),
                "sha": file_sha,
                "branch": branch,
            },
        )
    except GitHubError as e:
        return f"## ⚠️ Commit Failed\n\n`{str(e)[:100]}`"

    # ── Open PR ────────────────────────────────────────────────────────────
    try:
        pr = gh_post(
            f"/repos/{repo}/pulls",
            token,
            {
                "title": f"fix: {fix_plan.get('pr_title', f'Fix issue #{issue_number}')}",
                "body": _build_pr_body(fix_plan, issue_number, title),
                "head": branch,
                "base": default_br,
            },
        )
        pr_num = pr.get("number", "?")
        pr_url = pr.get("html_url", "")
        log_ctx.done(f"Autofix PR #{pr_num} created")
        return (
            f"## ✅ Autofix Complete!\n\n"
            f"Created **[PR #{pr_num}]({pr_url})**\n\n"
            f"**File:** `{target}` | **Branch:** `{branch}`\n\n"
            f"**Fix:** {fix_plan.get('explanation', '')}\n\n"
            "> ⚠️ Review before merging — AI fixes need human verification."
        )
    except GitHubError as e:
        if "422" in str(e):
            return (
                f"## ⚠️ PR Already Exists\n\nCheck open PRs from `{branch}`."
            )
        return f"## ⚠️ PR Failed\n\n`{str(e)[:100]}`"


# ── Private helpers ────────────────────────────────────────────────────────────


def _generate_fix_plan(
    title: str,
    body: str,
    target_file: str,
) -> Optional[dict]:
    """
    Ask LLM for a structured fix plan.
    Returns None when confidence < 0.6 or on any failure.
    """
    try:
        hint = f"Focus on file: {target_file}" if target_file else ""
        r, _ = router.ask(
            "Principal engineer. Generate precise minimal code fixes. JSON only.",
            f"""Issue: {title}\nDetails: {body}\n{hint}\n
Return JSON:
{{
  "target_file": "path/to/file.py",
  "pr_title": "description",
  "commit_message": "fix: what changed",
  "problem": "what is broken",
  "fix_description": "what this PR does",
  "explanation": "why this fixes it",
  "patch": "exact code change",
  "confidence": 0.8
}}
If confidence < 0.6 return {{"confidence": 0.0}}""",
            task="fix_command",
            max_tokens=1500,
        )

        # {"raw": text} means JSON extraction failed
        if "raw" in r and "confidence" not in r:
            log.warning(
                "autofix._generate_fix_plan: LLM returned non-JSON response"
            )
            return None

        if not r or float(r.get("confidence", 0)) < 0.6:
            return None

        return r

    except Exception as e:
        log.error(f"autofix._generate failed: {e}")
        return None


def _apply_fix(current: str, fix_plan: dict, title: str) -> str:
    """
    Apply fix_plan to current file content.
    Returns fixed file string, or current (unchanged) on failure.

    Sprint 8 fixes:
    - Send up to _MAX_FILE_CHARS (16 000) chars instead of [:4000].
      Files larger than the limit are truncated with an explicit marker so the
      LLM knows not to invent content for the missing tail.
    - Reject response if it is <70 % of original length (truncation indicator).
    - Log JSON extraction failures instead of silently returning current.
    """
    try:
        # Build safe file excerpt for LLM context
        file_for_llm, was_truncated = _safe_excerpt(current)

        r, _ = router.ask(
            "Code editor. Apply fix precisely. Return complete file. JSON only.",
            f"""Apply fix to file:
ISSUE: {title}
FIX: {fix_plan.get('patch', '')}

FILE{' (TRUNCATED — return only the shown portion, preserve rest)' if was_truncated else ''}:
```
{file_for_llm}
```

Return JSON: {{"fixed_content": "complete file content", "changed_lines": 2}}""",
            task="fix_command",
            max_tokens=4000,
        )

        # Sprint 8 fix: {"raw": text} = JSON extraction failed — log it
        if "raw" in r and "fixed_content" not in r:
            log.warning(
                "autofix._apply_fix: LLM returned non-JSON; cannot apply fix"
            )
            return current

        fixed = r.get("fixed_content", "")

        if not fixed or len(fixed) < 10:
            return current

        # Sprint 8 safety guard: if response is <70 % of original, the LLM
        # likely truncated the file — reject to avoid data loss.
        if len(fixed) < len(current) * 0.70:
            log.warning(
                f"autofix._apply_fix: response too short "
                f"({len(fixed)} vs {len(current)}) — rejecting to prevent truncation"
            )
            return current

        return fixed

    except Exception as e:
        log.error(f"autofix._apply_fix failed: {e}")
        return current


def _safe_excerpt(content: str) -> tuple[str, bool]:
    """
    Return (content_for_llm, was_truncated).
    Keeps up to _MAX_FILE_CHARS; appends truncation marker if cut.
    """
    if len(content) <= _MAX_FILE_CHARS:
        return content, False

    truncated = content[:_MAX_FILE_CHARS]
    truncated += _TRUNCATION_MARKER.format(limit=_MAX_FILE_CHARS)
    return truncated, True


def _get_default_branch(repo: str, token: str) -> str:
    try:
        return gh_get(f"/repos/{repo}", token).get("default_branch", "main")
    except Exception:
        return "main"


def _create_branch(repo: str, token: str, branch: str, base: str) -> None:
    """
    Create a new branch from the tip of `base`.

    Sprint 8 fix: `ref["object"]["sha"]` wrapped in KeyError guard.
    Previously an unexpected API payload (e.g. GitHub returns a list instead
    of a single object) raised an unhandled KeyError that was NOT caught by
    `except GitHubError` in run_autofix, silently crashing the handler.
    """
    ref = gh_get(f"/repos/{repo}/git/ref/heads/{base}", token)
    try:
        sha = ref["object"]["sha"]
    except (KeyError, TypeError) as e:
        raise GitHubError(
            f"Cannot read SHA for branch '{base}': unexpected API response. "
            f"Raw keys: {list(ref.keys()) if isinstance(ref, dict) else type(ref)}"
        ) from e

    gh_post(
        f"/repos/{repo}/git/refs",
        token,
        {"ref": f"refs/heads/{branch}", "sha": sha},
    )


def _build_pr_body(fix_plan: dict, issue_number: int, title: str) -> str:
    conf = int(float(fix_plan.get("confidence", 0.8)) * 100)
    return (
        f"## 🤖 Automated Fix — Issue #{issue_number}\n\n"
        f"**Issue:** {title}\n\n"
        f"### Problem\n{fix_plan.get('problem', '')}\n\n"
        f"### Fix\n{fix_plan.get('fix_description', '')}\n\n"
        f"### Why\n{fix_plan.get('explanation', '')}\n\n"
        f"---\nCloses #{issue_number}\n\n"
        f"> 🤖 Auto-generated | Confidence: {conf}% | Please review before merging."
    )


def _is_allowed(filepath: str) -> bool:
    """Return True if the file path is safe to auto-modify."""
    if not filepath or filepath in BLOCKED_PATHS:
        return False
    ext = "." + filepath.rsplit(".", 1)[-1] if "." in filepath else ""
    return ext in ALLOWED_EXTENSIONS
