"""
app/handlers/autofix.py - V4 Sprint 6: Auto-Fix Engine.
/autofix on issue → bot creates fix branch + PR automatically.
"""
import base64
import logging
from app.github.client import gh_get, gh_post, gh_put, GitHubError
from app.ai.router import router
from app.core.logger import EventLogger

log = logging.getLogger(__name__)
ALLOWED_EXTENSIONS = {".py", ".md", ".txt", ".yml", ".yaml", ".json", ".toml"}
BLOCKED_PATHS = {"app/github/auth.py", "server.py", ".env"}


def run_autofix(repo, issue_number, issue, token, target_file=""):
    log_ctx = EventLogger("autofix", repo=repo)
    title = issue.get("title", "")
    body = (issue.get("body") or "")[:2000]
    fix_plan = _generate_fix_plan(title, body, target_file)
    if not fix_plan:
        return "## ⚠️ Autofix Failed\n\nCould not generate fix. Try `/fix` instead."
    target = fix_plan.get("target_file", target_file)
    if not _is_allowed(target):
        return f"## ⚠️ Autofix Skipped\n\nCannot auto-modify `{target}`. Use `/fix` manually."
    try:
        file_data = gh_get(f"/repos/{repo}/contents/{target}", token)
        current = base64.b64decode(file_data["content"]).decode("utf-8")
        file_sha = file_data["sha"]
    except Exception as e:
        return f"## ⚠️ Autofix Failed\n\nCannot read `{target}`: `{str(e)[:100]}`"
    fixed = _apply_fix(current, fix_plan, title)
    if not fixed or fixed == current:
        return "## ⚠️ Autofix Skipped\n\nFix didn't change file. Use `/fix` for suggestions."
    branch = f"fix/bot-issue-{issue_number}"
    default_br = _get_default_branch(repo, token)
    try:
        _create_branch(repo, token, branch, default_br)
    except GitHubError as e:
        if "already exists" not in str(e):
            return f"## ⚠️ Branch Error\n\n`{str(e)[:100]}`"
    try:
        gh_put(f"/repos/{repo}/contents/{target}", token, {
            "message": (
                f"fix: {fix_plan.get('commit_message', f'fix issue #{issue_number}')}\n\n"
                f"Closes #{issue_number}\nAuto-generated by AI Repo Manager"
            ),
            "content": base64.b64encode(fixed.encode()).decode(),
            "sha": file_sha,
            "branch": branch,
        })
    except GitHubError as e:
        return f"## ⚠️ Commit Failed\n\n`{str(e)[:100]}`"
    try:
        pr = gh_post(f"/repos/{repo}/pulls", token, {
            "title": f"fix: {fix_plan.get('pr_title', f'Fix issue #{issue_number}')}",
            "body": _build_pr_body(fix_plan, issue_number, title),
            "head": branch,
            "base": default_br,
        })
        pr_num = pr.get("number", "?")
        pr_url = pr.get("html_url", "")
        log_ctx.done(f"Autofix PR #{pr_num} created")
        return (
            f"## ✅ Autofix Complete!\n\n"
            f"Created **[PR #{pr_num}]({pr_url})**\n\n"
            f"**File:** `{target}` | **Branch:** `{branch}`\n\n"
            f"**Fix:** {fix_plan.get('explanation', '')}\n\n"
            "> ⚠️ Review before merging — AI fixes need human verification."
        )
    except GitHubError as e:
        if "422" in str(e):
            return f"## ⚠️ PR Already Exists\n\nCheck open PRs from `{branch}`."
        return f"## ⚠️ PR Failed\n\n`{str(e)[:100]}`"


def _generate_fix_plan(title, body, target_file):
    try:
        hint = f"Focus on file: {target_file}" if target_file else ""
        r, _ = router.ask(
            "Principal engineer. Generate precise minimal code fixes. JSON only.",
            f"""Issue: {title}\nDetails: {body}\n{hint}\n
Return JSON:
{{
  "target_file": "path/to/file.py",
  "pr_title": "description",
  "commit_message": "fix: what changed",
  "problem": "what is broken",
  "fix_description": "what this PR does",
  "explanation": "why this fixes it",
  "patch": "exact code change",
  "confidence": 0.8
}}
If confidence < 0.6 return {{"confidence": 0.0}}""",
            task="fix_command", max_tokens=1500,
        )
        if not r or float(r.get("confidence", 0)) < 0.6:
            return None
        return r
    except Exception as e:
        log.error(f"autofix._generate failed: {e}")
        return None


def _apply_fix(current, fix_plan, title):
    try:
        r, _ = router.ask(
            "Code editor. Apply fix precisely. Return complete file. JSON only.",
            f"""Apply fix to file:\nISSUE: {title}\nFIX: {fix_plan.get('patch','')}\n
FILE:\n```\n{current[:4000]}\n```\n
Return JSON: {{"fixed_content": "complete file", "changed_lines": 2}}""",
            task="fix_command", max_tokens=4000,
        )
        fixed = r.get("fixed_content", "")
        return fixed if fixed and len(fixed) > 10 else current
    except Exception:
        return current


def _get_default_branch(repo, token):
    try:
        return gh_get(f"/repos/{repo}", token).get("default_branch", "main")
    except Exception:
        return "main"


def _create_branch(repo, token, branch, base):
    ref = gh_get(f"/repos/{repo}/git/ref/heads/{base}", token)
    sha = ref["object"]["sha"]
    gh_post(f"/repos/{repo}/git/refs", token, {
        "ref": f"refs/heads/{branch}", "sha": sha,
    })


def _build_pr_body(fix_plan, issue_number, title):
    conf = int(float(fix_plan.get("confidence", 0.8)) * 100)
    return (
        f"## 🤖 Automated Fix — Issue #{issue_number}\n\n"
        f"**Issue:** {title}\n\n"
        f"### Problem\n{fix_plan.get('problem','')}\n\n"
        f"### Fix\n{fix_plan.get('fix_description','')}\n\n"
        f"### Why\n{fix_plan.get('explanation','')}\n\n"
        f"---\nCloses #{issue_number}\n\n"
        f"> 🤖 Auto-generated | Confidence: {conf}% | Please review before merging."
    )


def _is_allowed(filepath):
    if not filepath or filepath in BLOCKED_PATHS:
        return False
    ext = "." + filepath.rsplit(".", 1)[-1] if "." in filepath else ""
    return ext in ALLOWED_EXTENSIONS
